import {
  Settings,
  FitnessCenter as Sport,
  Spa as WellBeing,
  Restaurant as Nutrition,
  Feedback,
  Info as Conditions,
  ExitToApp as Logout,
  Home,
} from "@material-ui/icons";
import { ReactComponent as Relaxation } from "../assets/images/relaxation.svg";

export const pages = {
  home: {
    key: "MY_PAGE",
    value: "/",
    title: "Meine Seite",
    icon: <Home />,
  },
  favorites: {
    value: "favorites",
    content: [
      {
        type: "Video",
        id: "1",
        tags: ["fit", "zwischendrin"],
        title:
          "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
        duration: "15:35 min",
        src: "https://www.youtube.com/embed/8ZAe3JETvkI",
        favorite: true,
      },
      {
        type: "Audio",
        id: "2",
        tags: ["tag1", "tag2"],
        title: "Traumreise auf eine einsame Insel",
        duration: "03:34 min",
        src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
        favorite: false,
      },
      {
        type: "Text",
        id: "3",
        tags: ["tag1", "tag2", "tag3"],
        title: "Spielend gesunde Ernährung",
        duration: "",
        content:
          "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
        favorite: true,
      },
      {
        type: "Audio",
        id: "4",
        tags: [],
        title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
        duration: "03:34 min",
        favorite: true,
      },
    ],
  },

  relaxation: {
    key: "RELAXATION_PAGE",
    value: "relaxation",
    title: "Entspannung",
    icon: <Relaxation />,
    subcategories: [
      {
        title: "Achtsamkeit",
        text: "Erlebe die Vorzüge der Achtsamkeitspraxis.",
        value: "mindfulness",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Meditation",
        text: "Gib deinem Geist Freiraum.",
        value: "meditation",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Yoga",
        text: "Yoga praktizieren mit unseren Videos.",
        value: "yoga",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Progressive Muskelentspannung",
        text: "Aktive Entspannung mithilfe deines Körpers.",
        value: "progressive-muscle-relaxation",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Autogenes Training",
        text: "Übe dich in der Selbstentspannung mit unseren Audioanleitungen.",
        value: "autogenous-training",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Körperreisen",
        text: "Finde Entspannung durch deine eigene Vorstellungskraft.",
        value: "body-travel",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Qi Gong",
        text: "Erreiche Entspannung durch Bewegung.",
        value: "qi-gong",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
    ],
  },

  fitness: {
    key: "FITNESS_PAGE",
    value: "fitness",
    title: "Fitness",
    icon: <Sport />,
    subcategories: [
      {
        title: "Workouts",
        text:
          "Kraft, Ausdauer oder allgemeine Fitness verbessern mit unseren Videos.",
        value: "workouts",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Yoga",
        text: "Yoga praktizieren mit unseren Videos.",
        value: "yoga",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Gesundheit",
        text: "Rückenschule, Pausenfit, Mobilisation und mehr.",
        value: "health",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
    ],
  },

  wellbeing: {
    key: "WELL_BEING_PAGE",
    value: "wellbeing",
    title: "Wohlbefinden",
    icon: <WellBeing />,
    subcategories: [
      {
        title: "Schlaf",
        text: "Entdecke wie sich Schlaf auf deinen Alltag auswirkt.",
        value: "sleep",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Entspannung",
        text: "Finde die richtige Form der Entspannung für dich.",
        value: "relaxation",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Zeitmanagement",
        text: "Finde deine passenden Zeitmanagement-Strategien.",
        value: "time-management",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Methoden",
        text: "Lerne Strategien für dein Wohlbefinden kennen.",
        value: "methods",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
    ],
  },

  nutrition: {
    key: "NUTRITION_PAGE",
    value: "nutrition",
    title: "Ernährung",
    icon: <Nutrition />,
    subcategories: [
      {
        title: "Mensa",
        text: "Aktueller Speiseplan der Mensa an der Uni Regensburg.",
        value: "mensa",
      },
      {
        title: "Infobereich",
        text: "Nährstoffe, Grundumsatz, Rezepte und mehr.",
        value: "info",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
      {
        title: "Mythencheck",
        text:
          "Wusstest du, dass eine Paprika mehr Vitamin C enthält als eine Orange?",
        value: "myth-check",
        content: [
          {
            type: "Video",
            id: "1",
            tags: ["fit", "zwischendrin"],
            title:
              "Tolle Rückenübung für zwischendurch - werde fit und mache diesen Titel immer noch etwas länger",
            duration: "15:35 min",
            src: "https://www.youtube.com/embed/8ZAe3JETvkI",
            favorite: true,
          },
          {
            type: "Audio",
            id: "2",
            tags: ["tag1", "tag2"],
            title: "Traumreise auf eine einsame Insel",
            duration: "03:34 min",
            src: "https://glpro.s3.amazonaws.com/_util/smpte/111.mp3",
            favorite: false,
          },
          {
            type: "Text",
            id: "3",
            tags: ["tag1", "tag2", "tag3"],
            title: "Spielend gesunde Ernährung",
            duration: "",
            content:
              "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet,",
            favorite: true,
          },
          {
            type: "Audio",
            id: "4",
            tags: [],
            title: "Entspannung auf der grünen Wiese... Was weiß denn ich...",
            duration: "03:34 min",
            favorite: true,
          },
        ],
      },
    ],
  },
  settings: {
    key: "SETTINGS_PAGE",
    value: "/settings",
    title: "Einstellungen",
    icon: <Settings />,
  },
  feedback: {
    key: "FEEDBACK_PAGE",
    value: "/feedback",
    title: "Feedback",
    icon: <Feedback />,
  },
  imprint: {
    key: "IMPRINT_PAGE",
    value: "/imprint",
    title: "Impressum",
    icon: <Conditions />,
  },
  conditions: {
    key: "CONDITIONS_PAGE",
    value: "/conditions",
    title: "AGB",
    icon: <Conditions />,
  },

  logout: {
    key: "LOGIN_PAGE",
    value: "/login",
    title: "Abmelden",
    icon: <Logout />,
  },
};
export const week = ["Mo", "Di", "Mi", "Do", "Fr"];

export const meals = {
  mainDish: "HG",
  garnish: "B",
  dessert: "N",
};

export const mensaContentInfo = {
  V: "Vegetarisch",
  VG: "Vegan",
  G: "Geflügel",
  S: "Schwein",
  R: "Rind",
  L: "Lamm",
  W: "Wild",
  F: "Fisch",
  A: "Alkohol",
  B: "Bio",
};
export const mensaAdditionalInfo = {
  1: "Farbstoff",
  2: "Konservierungsstoff",
  3: "Antioxidationsmittel",
  4: "Geschmacksverstärker",
  5: "geschwefelt",
  6: "geschwärzt",
  7: "gewachst",
  8: "Phosphat",
  9: "Süssungsmittel Saccharin",
  10: "Süssungsmittel Aspartam",
  11: "Süssungsmittel Cyclamat",
  12: "Süssungsmittel Acesulfam",
  13: "chininhaltig",
  14: "coffeinhaltig",
  15: "gentechnisch verändert",
  16: "Sulfite",
  17: "Phenylalanin",
  AA: "Weizengluten",
  AB: "Roggengluten",
  AC: "Gerstengluten",
  AD: "Hafergluten",
  AE: "Dinkelgluten",
  AF: "Kamutgluten",
  B: "Krebstiere",
  C: "Eier",
  D: "Fisch",
  E: "Erdnüsse",
  F: "Soja",
  G: "Milch und Milchprodukte",
  HA: "Mandel",
  HB: "Haselnuss",
  HC: "Walnuss",
  HD: "Cashew",
  HE: "Pecannuss",
  HF: "Paranuss",
  HG: "Pistazie",
  HH: "Macadamianuss",
  HI: "Queenslandnuss",
  I: "Sellerie",
  J: "Senf",
  K: "Sesamsamen",
  L: "Schwefeldioxid und Sulfite",
  M: "Lupinen",
  N: "Weichtiere",
  O: "Nitrat",
  P: "Nitritpökelsalz",
};
